# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 21:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CLSniper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.TextField(max_length=30)),
                ('query', models.TextField(max_length=140)),
                ('min_price', models.IntegerField(blank=True, null=True)),
                ('max_price', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('search_titles', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.TextField()),
                ('price', models.IntegerField()),
                ('url', models.URLField()),
                ('post_id', models.TextField()),
                ('date', models.DateTimeField()),
                ('sniper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sniper.CLSniper')),
            ],
        ),
    ]
