# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sniper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clsniper',
            name='query',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='clsniper',
            name='site',
            field=models.TextField(max_length=30),
        ),
    ]
