# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sniper', '0003_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='clsniper',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
