# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sniper', '0004_clsniper_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='clsniper',
            name='search_titles',
            field=models.BooleanField(default=False),
        ),
    ]
